# Generated by Django 2.2.2 on 2019-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simodib_v1', '0003_portalsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurir',
            name='status_akun',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
