# Generated by Django 2.2.2 on 2019-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simodib_v1', '0004_kurir_status_akun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='rices',
        ),
        migrations.AddField(
            model_name='takendistribution',
            name='status_antar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
