# Generated by Django 2.2.2 on 2019-07-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simodib_v1', '0006_auto_20190714_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='prices',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detailorder',
            name='value',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rice',
            name='price',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rice',
            name='stock',
            field=models.IntegerField(max_length=100),
        ),
    ]
