# Generated by Django 2.2.2 on 2019-07-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simodib_v1', '0008_auto_20190719_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='prices',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
