# Generated by Django 2.2.2 on 2019-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simodib_v1', '0009_auto_20190720_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='statusOerder',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
