# Generated by Django 2.2.2 on 2019-07-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simodib_v1', '0010_distribution_statusoerder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='statusOerder',
            new_name='statusOrder',
        ),
    ]
