# Generated by Django 2.2.2 on 2019-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simodib_v1', '0011_auto_20190723_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='takendistribution',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
