# Generated by Django 2.2.2 on 2019-08-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simodib_v1', '0013_remove_takendistribution_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsignup',
            name='token_kurir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalsignup',
            name='token_manager',
            field=models.TextField(blank=True, null=True),
        ),
    ]
